### ISSUE TITLE
常盤祭の詳細を追加

### ISSUE THREAD

**Issue by Nanan65537** [ynufes-tech/22tokiwa-countdown#9]

**Comment by Shion1305** [comment]
一応この日時と時間の情報は追加お願いします!

10/28(金) 13:00-19:00、10/29 (土) 09:00-19:00、10/30(日) 09:00-15:00

**Comment by Nanan65537** [comment]
書く内容は
大学祭のテーマ, 開催日程, アクセス
で大丈夫ですか？

**Comment by Nanan65537** [comment]
書く内容
日付: カウントダウンの上
星彩の文字: 一番上でっかく(常識の範囲で)

**Comment by Shion1305** [comment]
ありがとうございます!お疲れさまでした
